### ISSUE TITLE
Feature Request: Mute/Unmute in-game

### ISSUE THREAD

**Issue by xtagon** [smallsco/mojave#8]
Hi @smallsco,

As always, loving the new updates to Mojave. So much fun.

It would be nice to be able to turn on/off the music and sound effects from the in-game view. Currently you have to leave the game and go back to the main menu, change it in the settings, and start a new game.

Maybe a hotkey? Maybe a way already exists? Thought I'd ask 🙂

**Comment by smallsco** [comment]
There currently isn't any way to toggle the audio while in-game, but it shouldn't be too difficult to implement a hotkey or something similar. I'll look into it!

**Comment by smallsco** [comment]
Hey @xtagon ,

I've just published version 3.3.1, which uses the F4 key to toggle the music and SFX during a game. You can also use F5 to toggle fullscreen mode, and the F6 through F12 keys map to the control buttons in the game UI. Hope this works for you! :)

**Comment by xtagon** [comment]
Awesome thank you so much!!
